### ISSUE TITLE
Remove "current password" check in account settings for cobot users

### ISSUE THREAD

**Issue by mntmn** [mntmn/lets-chat#3]

**Comment by plomlompom** [comment]
Merged the account settings box for cobot-auth'd users with the profile settings box in the last commit, with the new box expecting no password. (In the non-cobot-auth setup, the account settings box for good reason funnels the manipulation of login-critical data – username, password – through a second auth test. But for cobot oauth logins, the data manipulated here either does not exist – passwords – or is no longer login-critical.)
